### ISSUE TITLE
Request: fio

### ISSUE THREAD

**Issue by FrederikLeed** [UnRAIDES/unRAID-NerdTools#104]
fio was part of nerdpack at some point, but is not part of Nerdtools and not part of unraid it seems. ?

root@URTEST:/mnt/ssd# fio
bash: fio: command not found

**Comment by Mcklaren** [comment]
Hi,

NerdTools is based on nerdpack but it is an independent project and does not have all the packages that nerdpack had.

Yet it has been added in the version of NerdTools 2024.01.27.

Best regards.
