### ISSUE TITLE
Problems with Python3 Package

### ISSUE THREAD

**Issue by DjangoDurano** [UnRAIDES/unRAID-NerdTools#105]
Hello,

I updated the python3.9 package, after that I got some issues with my python program. I don't have this issue with the previous build.
I got an ctypes error:

```
import ctypes
File "/usr/lib64/python3.9/ctypes/__init__.py", line 8, in
from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory```

Seems to be that there is some error within the build. I searched google, and read that maybe that can be the issue.

**Comment by Mcklaren** [comment]
Hi,

The problem is that unraid has libffi-3.4.4 which is the current version of slackware.

We have added version 3.3 but you have to use it at your own risk and before installing libffi-3.3 you have to delete the one that comes installed with unraid, for this you can use the command removepkg libffi-3.4.4.

Best regards.

**Comment by DjangoDurano** [comment]
@Mcklaren 
Can you explain this in detail for me please?
Unraid uses libffi-3.4.4 this is newer than your libffi-3.3 correct?
I don't update my unraid system to a newer version, libffi should be same version as before. I only update the python-3.9 package from nerdtools. Before I updated python my python script worked without any issues.
After I updated python I got the libffi error.
Have you downgrade libffi version in your build script?
I'm not very deep into building slackware packages, but I don't get on the point why the same libffi version as before got me an error on your newer python package.


Best regards.
