### ISSUE TITLE
NVME-CLI installs wrong package

### ISSUE THREAD

**Issue by C4Wiz** [UnRAIDES/unRAID-NerdTools#107]
![Screenshot 2024-01-28 at 11 11 17 AM](https://github.com/UnRAIDES/unRAID-NerdTools/assets/3883521/0aac5848-6565-4b4d-af29-6cd2aefbfc59)

selecting nvme-cli downloads npth and then tries to instal nvme-cli

**Comment by Mcklaren** [comment]
Hi,

This package has a problem.

We have tried adding the unmodified package but it keeps giving errors.
We are working on it.

Thank you.

Best regards.

**Comment by Mcklaren** [comment]
Hi,

The error is fixed on 2024.02.05 version.

Best regards.
