### ISSUE TITLE
Add python3.9 package that solve ctypes issue (own build included)

### ISSUE THREAD

**Issue by DjangoDurano** [UnRAIDES/unRAID-NerdTools#109]
Hello,

I build a python-3.9.18 package that included pip and setuptools and solved the issue from [here](https://github.com/UnRAIDES/unRAID-NerdTools/issues/105).
I build direct on latest unraid version. 

[Link to python package](https://github.com/DjangoDurano/Unraid_Packages/raw/main/python3-3.9.18-x86_64-1.txz)

Best regards

**Comment by Mcklaren** [comment]
Ok,
we only add official packages.

If you need that package you can use the installation method proposed by limetech.

Best regards.
