### ISSUE TITLE
Add information on how to add packages

### ISSUE THREAD

**Issue by maxwai** [UnRAIDES/unRAID-NerdTools#26]
I think that a description on how to add packages to the plugin, so what needs to be checked, what files need to be updated, etc... will help a lot offloading the work to the community.

Also, if the community can more easily add packages, the plugin would grow more and updates to packages would come faster.

As a suggestion I propose to include following information in the README.md on how to add packages:

* For what architecture and distro a package need to be build/compiled for (maybe even an example with one packages what steps are needed if the package is not available already compiled and needs to be compiled on the own system)
* What files need to be updated
* What needs to be tested before opening up a Merge Request

Of course this introduces the problem of verifying that a package wasn't modified from the source. For that I propose that for packages that were already found compiled, the link to the checksum could be given (so not the checksum directly but the link of where to find the checksum in combination with the package itself) to verify the package.  
For packages that need to be compiled manually because they are not available in the public package lists, I propose, instead of adding the compiled package directly, which can't be easily verified, to open a Issue with the necessary commands to compile it. So that would be the commands to download the source, extract it, build and compile the package, and package it again for the plugin.

**Comment by UnRAIDES** [comment]
Thank you very much for the interest shown in how you can collaborate in the project, but being a new project we are the developers are evaluating options for contribution. As soon as we have a solution on how we want you to help us you will be informed.
