### ISSUE TITLE
Request: Bluez

### ISSUE THREAD

**Issue by Supergamerx3000** [UnRAIDES/unRAID-NerdTools#31]
Can you please add bluez to the nerd-tools package.

I need bluez because I want to add a Bluetooth stick to the homeassistant docker.

Bluez was added to the old Nerd Tools and there is a issue on the other repo

https://github.com/dmacias72/unRAID-NerdPack/issues/6

https://github.com/UnRAIDES/plugin-UnRAID/issues/6

**Comment by TRusselo** [comment]
same here - tryin to get home assistant working with bluetooth
nerd pack has bluez 5.50
bluez is currently 5.66
known working version with home assistant is 5.64

see videohttps://youtu.be/ZXvcdI3mQuA
keep watching after 3:20 when he gets to his problem ect.
he had to build 6.64 for his system

**Comment by Mcklaren** [comment]
Hi,

package added on 2024.01.06 version.

Best regards.
