### ISSUE TITLE
Request: nmap

### ISSUE THREAD

**Issue by juhannc** [UnRAIDES/unRAID-NerdTools#44]
I think `nmap` would be a welcome addition to the NerdTools package.

**Comment by kennymc-c** [comment]
It definitely would make sense to include this tool. There was already a request for the old NerdPack https://github.com/dmacias72/unRAID-NerdPack/issues/29

**Comment by Mcklaren** [comment]
Hi,

Fixed on version 2024.01.07

Best regards.
