### ISSUE TITLE
Request: RAR2FS

### ISSUE THREAD

**Issue by thewho2018** [UnRAIDES/unRAID-NerdTools#56]
https://github.com/hasse69/rar2fs
https://github.com/hasse69/rar2fs/releases
https://slackbuilds.org/repository/15.0/system/rar2fs/

Would be so helpful because i can't get the docker to work without file rights problems. Old NerdPack had a old version with bugs that was a bit problematic for me with shutting down unRAID.

It's 2 versions old but something at least!

**Comment by thewho2018** [comment]
https://slackbuilds.org/repository/15.0/system/rar2fs/

It's 2 builds old but something at least!

**Comment by thewho2018** [comment]
https://github.com/hasse69/rar2fs/releases

**Comment by taulen** [comment]
I really hope this can be added soon, would be very much appreciated.

**Comment by Mcklaren** [comment]
Hi,
package add on 2023.07.18 version.

Best regard.
