### ISSUE TITLE
You either changed unRiad versions or deleted....

### ISSUE THREAD

**Issue by Losiyu** [UnRAIDES/unRAID-NerdTools#73]
When I finish install the package and back to the nerdtool screen, it shows a message:

You either changed unRAID versions or deleted your downloaded packages. CIick Download or the Apply button below to download and install your selected packages.

Version:
NerdTools: 2023.05.07 
Unraid OS: 6.11.5

**Comment by jsavargas** [comment]
Hello, you can add a screenshot of the message that appears to you, in order to have more context.

**Comment by Mcklaren** [comment]
Hello,
Please update NerdTools to version 2023.05.14 and if you has problem try too push on Button "check for updates".

Best regard.

**Comment by Mcklaren** [comment]
Hi,

If you need help of new, reopen please.

Best regards.

**Comment by dizhuangh** [comment]
> Hi,
> 
> If you need help of new, reopen please.
> 
> Best regards.

![1700991703902](https://github.com/UnRAIDES/unRAID-NerdTools/assets/56089948/c2ba3ff4-247c-43c2-bcfb-e26666553910)
