### ISSUE TITLE
Bug: Missing SSL Support in latest python3

### ISSUE THREAD

**Issue by Lanjelin** [UnRAIDES/unRAID-NerdTools#74]
Long story short, was to install borgmatic on my main server, after testing on testserver, and running it on my smarthome server.

```bash
~ python3 -m pip install borgmatic
........
ERROR: Could not find a version that satisfies the requirement borgmatic (from versions: none)
ERROR: No matching distribution found for borgmatic
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.
```

```bash
~ python3 -m ssl
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.9/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: libssl.so.3: cannot open shared object file: No such file or directory
```

Realized (eventually) that my main server was running **python3-3.9.16-x86_64-3_nerdtools.txz** while the others were running **python3-3.9.16-x86_64-1_nerdtools.txz**.

Removing **-3**, replacing it with **-1** from one of the other servers also fixed the issue.

Edit: Another this is that all 3 of my servers showed from the GUI that they had python3-3.9.16-x86_64-3_nerdtools.txz installed and up-to-date, while in fact 2 of them were having python3-3.9.16-x86_64-1_nerdtools.txz

**Comment by Mcklaren** [comment]
Hi,
This problem is fixed on version 2023.05.14.

Please uninstall python3, push on Button "check for updates" and install python3 of new.

Best regard.
