### ISSUE TITLE
Request: jq

### ISSUE THREAD

**Issue by nukewarrior** [UnRAIDES/unRAID-NerdTools#81]
jq:https://jqlang.github.io/jq/

jq is a lightweight and flexible command-line JSON processor

thx

**Comment by Mcklaren** [comment]
Hi,
Do you really need this package? I see the github project and the latest version is from 2018. I really think that already abandoned or old projects are not worth adding those packages.

**Comment by nukewarrior** [comment]
> Hi, Do you really need this package? I see the github project and the latest version is from 2018. I really think that already abandoned or old projects are not worth adding those packages.

No,
jq is in unraid's base package ,sorry for my mistake to open this issue.
