### ISSUE TITLE
Request: nvme-cli package

### ISSUE THREAD

**Issue by Mcklaren** [UnRAIDES/unRAID-NerdTools#91]
https://forums.unraid.net/topic/129200-plug-in-nerdtools/?do=findComment&comment=1279884

**Comment by billchurch** [comment]
+1 on this. 

For reference, the slack package is here: http://slackware.absolutehosting.net/pub/slackware/slackware64-15.0/slackware64/ap/nvme-cli-1.16-x86_64-1.txz

**Comment by Mcklaren** [comment]
Hi,

Package added in the version 2024.01.27

Best regards.
