### ISSUE TITLE
Typo in remove script looks as though it will fail to remove *_nerdtools.txz

### ISSUE THREAD

**Issue by kcpants** [UnRAIDES/unRAID-NerdTools#94]
https://github.com/UnRAIDES/unRAID-NerdTools/blob/d1a1ef24ece29134501c71a3302bd04d9d431e09/plugin/NerdTools.plg#L227

The line above appears to remove all nerdtool txz's from the non-existant `/boot/exta` directory rather than `/boot/extra`. In other words, **extra** appears to have a typo (it is missing an 'r').

Note: I have not verified this issue experimentally. I noticed it by inspecting the code.

**Comment by Mcklaren** [comment]
Hi,

Fixed on version 2024.01.06b.

Thank you very much by your help.

Best regards.
