### ISSUE TITLE
Missing Dependency libnsl.so.3

### ISSUE THREAD

**Issue by monogoat** [UnRAIDES/unRAID-NerdTools#95]
Updated Unraid to the newest version and replaced nerdpack with nerdtools. Installed irssi from nerdtools, but it won't launch:

irssi: error while loading shared libraries: libnsl.so.3: cannot open shared object file: No such file or directory

**Comment by Mcklaren** [comment]
Hi,

Fixed on version 2024.01.06b.

Try and if you has problem reopen the issues please.

Best regards.
