### ISSUE TITLE
Request: aria2 download manager

### ISSUE THREAD

**Issue by luzfcb** [UnRAIDES/unRAID-NerdTools#99]
From the project [home page](https://aria2.github.io/)

> aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.

It's a very good alternative to Axel download manager.

https://aria2.github.io/manual/en/html/README.html

https://slackbuilds.org/repository/15.0/network/aria2/

https://wiki.archlinux.org/title/aria2

**Comment by Mcklaren** [comment]
Hi,

package added on 2024.01.06 version.

Best regards.
